<?php
$app->get('/get-excel/',function () use($app){
  $fecha = getdate();
  $mes = $fecha['mon']-1;
  $spreadsheet = new PhpOffice\PhpSpreadsheet\Spreadsheet();
  $sheet = $spreadsheet->getActiveSheet();
  $spreadsheet->getActiveSheet()->getColumnDimension('A')->setWidth(12);
  $spreadsheet->getActiveSheet()->getColumnDimension('B')->setWidth(12);
  $spreadsheet->getActiveSheet()->getColumnDimension('C')->setWidth(12);
  $spreadsheet->getActiveSheet()->getColumnDimension('D')->setWidth(12);
  $spreadsheet->getActiveSheet()->getColumnDimension('E')->setWidth(12);
  $spreadsheet->getActiveSheet()->getColumnDimension('F')->setWidth(12);
  $spreadsheet->getActiveSheet()->getColumnDimension('G')->setWidth(12);
  $spreadsheet->getActiveSheet()->getColumnDimension('H')->setWidth(12);
  $spreadsheet->getActiveSheet()->getColumnDimension('I')->setWidth(12);
  $spreadsheet->getActiveSheet()->getColumnDimension('J')->setWidth(12);
  $spreadsheet->getActiveSheet()->getColumnDimension('K')->setWidth(12);
  $spreadsheet->getActiveSheet()->getColumnDimension('L')->setWidth(12);
  $spreadsheet->getActiveSheet()->getColumnDimension('M')->setWidth(12);
  $spreadsheet->getActiveSheet()->getColumnDimension('N')->setWidth(12);
  $spreadsheet->getActiveSheet()->getColumnDimension('O')->setWidth(12);

  $sheet->setCellValue('A1','Movimiento');
  $sheet->getStyle('A1')->getAlignment()->setWrapText(true);
  $sheet->setCellValue('B1','No. Económico');
  $sheet->getStyle('B1')->getAlignment()->setWrapText(true);
  $sheet->setCellValue('C1','No. de Serie');
  $sheet->getStyle('C1')->getAlignment()->setWrapText(true);
  $sheet->setCellValue('D1','Kva');
  $sheet->getStyle('D1')->getAlignment()->setWrapText(true);
  $sheet->setCellValue('E1','voltaje');
  $sheet->getStyle('E1')->getAlignment()->setWrapText(true);
  $sheet->setCellValue('F1','Fecha Fab.');
  $sheet->getStyle('F1')->getAlignment()->setWrapText(true);
  $sheet->setCellValue('G1','Fases');
  $sheet->getStyle('G1')->getAlignment()->setWrapText(true);
  $sheet->setCellValue('H1','Tipo');
  $sheet->getStyle('H1')->getAlignment()->setWrapText(true);
  $sheet->setCellValue('I1','Marca o Razón social');
  $sheet->getStyle('I1')->getAlignment()->setWrapText(true);
  $sheet->setCellValue('J1','No. de reserva en SAP R3');
  $sheet->getStyle('J1')->getAlignment()->setWrapText(true);
  $sheet->setCellValue('K1','Nuevo o usado');
  $sheet->getStyle('K1')->getAlignment()->setWrapText(true);
  $sheet->setCellValue('L1','Motivo del movimiento');
  $sheet->getStyle('L1')->getAlignment()->setWrapText(true);
  $sheet->setCellValue('M1','Ubicación Geográfica');
  $sheet->getStyle('M1')->getAlignment()->setWrapText(true);
  $sheet->setCellValue('N1','Dirección');
  $sheet->getStyle('N1')->getAlignment()->setWrapText(true);
  $sheet->setCellValue('O1','Fecha');
  $sheet->getStyle('O1')->getAlignment()->setWrapText(true);
  $sheet->setCellValue('P1','Area Dist.');
  $sheet->getStyle('P1')->getAlignment()->setWrapText(true);
  $st = $app->db->prepare("SELECT r.id,r.fecha,r.ubicacion,r.responsable,r.num_circuito,r.causa,r.coordenadas,r.marca,r.capacidad,r.fases,r.voltmed,r.voltbaj,r.no_serie,r.no_econo,r.tipo,r.tipo2,r.aceite,r.peso,r.causadan,r.clavedan,r.condiciones,i.marca marcai,i.capacidad capacidadi,i.fases fasesi,i.voltmed voltmedi,i.voltbaj voltbaji,i.no_serie no_seriei,i.no_econo no_econoi,i.tipo tipoi,i.tipo2 tipo2i,i.aceite aceitei,i.peso pesoi,i.causa causai FROM instalado AS i JOIN retirado AS r ON(r.id_instalado = i.id) WHERE r.fecha LIKE '%/$mes/%'");
  $st->setFetchMode(PDO::FETCH_OBJ);
  $st->execute();
  $data = $st->fetchAll();
  $i = 2;
  foreach($data as $value){
    $sheet->setCellValue('A'.$i,$value->id);
    //$sheet->getStyle('A'.$i)->getAlignment()->setWrapText(true);
    $sheet->setCellValue('B'.$i,$value->no_econo);
    // $sheet->getStyle('B'.$i)->getAlignment()->setWrapText(true);
    $sheet->setCellValue('C'.$i,$value->no_serie);
    // $sheet->getStyle('C'.$i)->getAlignment()->setWrapText(true);
    $sheet->setCellValue('G'.$i,$value->fases);
    // $sheet->getStyle('G'.$i)->getAlignment()->setWrapText(true);
    $sheet->setCellValue('H'.$i,$value->tipo.$value->tipo2);
    // $sheet->getStyle('H'.$i)->getAlignment()->setWrapText(true);
    $sheet->setCellValue('I'.$i,$value->marca);
    // $sheet->getStyle('I'.$i)->getAlignment()->setWrapText(true);
    $sheet->setCellValue('K'.$i,$value->condiciones);
    // $sheet->getStyle('K'.$i)->getAlignment()->setWrapText(true);
    $sheet->setCellValue('L'.$i,$value->causa);
    // $sheet->getStyle('L'.$i)->getAlignment()->setWrapText(true);
    $sheet->setCellValue('M'.$i,$value->coordenadas);
    // $sheet->getStyle('M'.$i)->getAlignment()->setWrapText(true);
    $sheet->setCellValue('N'.$i,$value->ubicacion);
    // $sheet->getStyle('N'.$i)->getAlignment()->setWrapText(true);
    $sheet->setCellValue('O'.$i,$value->fecha);
    // $sheet->getStyle('O'.$i)->getAlignment()->setWrapText(true);
    $i++;
  }
  $writer = new PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
  header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  header('Content-Disposition: attachment; filename="file.xlsx"');
  $writer->save("php://output");
})->name('get-excel');
?>
